### ISSUE TITLE
Definition of color of Boolean dashboard variable

### ISSUE THREAD

**Issue by JoergTiedemann** [maakbaas/esp8266-iot-framework#108]
Hi
Just for my deeper understanding  
Where is the definition of the colors for the true and false value of a Boolean dashboard variable made ?
You use the classname true and false for that, but where is the css definition for this classes located ?

**Comment by maakbaas** [comment]
Sorry for the delayed response. You can find it starting from this line:

https://github.com/maakbaas/esp8266-iot-framework/blob/b2bf375e6b97f95b07a525e86ddc60a83ab476fc/gui/js/comp/DashboardItems.js#L29
