### ISSUE TITLE
Asynchronous Fetch requests

### ISSUE THREAD

**Issue by joshbmarshall** [maakbaas/esp8266-iot-framework#111]
Hi I'm wanting to post data to a webserver on a regular basis. The problem I have is that when it is waiting for a response the main loop is blocked and other processes stop.

Is there a way that I can post the data and not block the main loop?

I did look at RTOS as an option but looks like for this project on 8266 it's not an option. Please correct me if I'm wrong!

**Comment by maakbaas** [comment]
If you look at the example code in the documentation (for GET, but the principle for POST is the same), you see the following structure:

```c
fetch.GET("https://www.google.com");

while (fetch.busy())
{
    if (fetch.available())
    {
        Serial.write(fetch.read());
    }
}

fetch.clean();
```

This code is blocking but it is easy to see how you would implement this in a non-blocking way. What it does is it posts the requests, and then checks if new bytes are available to process. 

You could change this into something like `if (fetch.busy() && fetch.available())`, and then read a single or multiple bytes and integrate this with the rest of your logic. In this way reading the response will be more spread out, and you could do other things in between.

If you are talking only about the time it takes to process the .GET or .POST command, then I am afraid there is no way around this.
