### ISSUE TITLE
Question - redirect the browser to an URL inner loop

### ISSUE THREAD

**Issue by Eisbaeeer** [maakbaas/esp8266-iot-framework#121]
Hi.
New question. I should redirect the client browser to a external URL after processing internaly things in loop.
I use the fetch process to get an TOKEN from a external page. Now the received token should integrated in a URL and the client browser should redirected to that URL.
The external URL is: 'https://www.facebook.com/device?user_code=TOKEN'

With "normal" http server I would send that to the client via:
`client.print("<HEAD>");
client.print("<meta http-equiv=\"refresh\" content=\"0;url=https://www.facebook.com/device?user_code=<TOKEN>\">");
client.print("</head>");   `  
 
My target: After getting the TOKEN from facebook, the user should redirect to the URL above.
Greets Lars

**Comment by Eisbaeeer** [comment]
Again. Is it possible to realize that on a other way. How can I provide a dynamic link, filled from loop() in dashboard?
This should be a clickable link as example:
![image](https://user-images.githubusercontent.com/4928271/131552076-31174253-ba35-4a3b-bf77-1596946b0e96.png)

Thanks for ideas or hints.
Greets Lars

**Comment by maakbaas** [comment]
Sorry for the huge delay in responding. Right now I am too busy to work on new features myself (As you probably figured out from this delay ;)). Proposed features will only be handled in the form of pull requests.

**Comment by Eisbaeeer** [comment]
> Proposed features will only be handled in the form of pull requests.

Wow, OK. This means you only will do bugfixes in future or is this project dead on now?
You created a great framework!

**Comment by maakbaas** [comment]
The project is not dead, I will keep doing bugfixes, and keep integrating pull requests for new features. 

But right now my priorities do not allow me to spend time on the development of new features myself. Of course in the future that might change again.

**Comment by Eisbaeeer** [comment]
@maakbaas Good to know! Thank you verry much for your statement. This will be fine because the project is awesome 👌

**Comment by aaronse** [comment]
> The project is not dead, I will keep doing bugfixes, and keep integrating pull requests for new features.
> 
> But right now my priorities do not allow me to spend time on the development of new features myself. Of course in the future that might change again.

Totally understand.  Thank you for creating this project.  I appreciate the time and effort you and other contributors have invested.  Look forward to seeing/helping this project continue to evolve.
