### ISSUE TITLE
Device goes straight to Captive Portal even when wifi is defined if AP is not available

### ISSUE THREAD

**Issue by joshbmarshall** [maakbaas/esp8266-iot-framework#122]
Hi I have a situation where a wireless cellular adapter is powered by the same (battery) power as the ESP8266 (a Lolin D1 Pro). 

The wifi adapter takes 20-30 seconds to start up and advertise its WiFi.

I have the default 60000 ms timeout set in the wifimanager setup call, but the device goes to captive portal only a second or so after starting up.

If the wifi adapter is turned on and settles before I turn on the ESP device, it connects every time.

Since the ESP in captive portal mode never retries the stored wifi details, I have to restart it to get it to connect again.

**Comment by maakbaas** [comment]
Should be fixed in the commit above which will be part of the upcoming release!

the default `waitForConnectResult` only checks for `WL_DISCONNECTED`, but I have modified it to also check for `WL_NO_SSID_AVAIL`
