### ISSUE TITLE
Option to add headers to fetches

### ISSUE THREAD

**Issue by TyIsI** [maakbaas/esp8266-iot-framework#13]
Feature Request:

Some platforms require authenticated headers in their HTTP requests.

The `fetch` interface currently doesn't support custom HTTP headers.

**Comment by maakbaas** [comment]
Good suggestion. Do you propose adding the headers as a string, or in some other format?

**Comment by TyIsI** [comment]
I think for simplicity as simple String array solution should suffice. It would be easy to iterate and call addHeader.

Let me see if I can create a PR for this (and also add the missing methods).
