### ISSUE TITLE
Cant connect to own webserver via WAN & LAN

### ISSUE THREAD

**Issue by kkuez** [maakbaas/esp8266-iot-framework#131]
I have got a tomcat running a java rest https application. It is reachable via WAN and locally in LAN. It works on Android and curl, but when I make a request with the ESP I cant connect.
Requests to other addresses like google.com or github.com work fine over https.
Using http in the url instead of https works fine, too (Meaning 400 answer from server).

```
  const char *host = "https://192.168.178.119:8080";
  fetch.begin(host);
  fetch.addHeader("111", "111"); 
  fetch.addHeader("222", "222");
  int httpCode = fetch.GET(host);
  if (httpCode == HTTP_CODE_OK)
  {
    while (fetch.busy())
    {
      if (fetch.available())
      {
        Serial.write(fetch.read());
      }
    }
  }
  else
  {
    Serial.printf("HTTP-Status: %d\n", httpCode);
  }

  fetch.clean();
```

Output:
```Starting HTTPS Framework...  // Own Serial.print
fpm close 3
mode : sta(8c:aa:b5:78:87:3b)
add if0
scandone
state: 0 -> 2 (b0)
state: 2 -> 3 (0) 
state: 3 -> 5 (10)
add 0
aid 1
cnt

connected with Auenland, channel 1
dhcp client start...
ip:192.168.178.50,mask:255.255.255.0,gw:192.168.178.1
Connected to stored WiFi details
192.168.178.50
[HTTP-Client] failed connect to Host , Port: 0
HTTP-Status: -1  // Own Serial.print
Looping...  // Own Serial.print
pm open,type:2 0
```

Feel free to get in contact with me so I can give you my servers url for testing purposes :)

**Comment by maakbaas** [comment]
You can use the contact form on maakbaas.com to share your server so I can have a look!

**Comment by kkuez** [comment]
Any reason for the closing?

**Comment by maakbaas** [comment]
I sent you a response by e-mail.

**Comment by kkuez** [comment]
Great, thank you!
So, for documentation purposes Ill write what went wrong here.

If you intent to connect your esp to your own webserver, make sure its certificate has not expired x)
Good luck and thanks again maakbaas!
