### ISSUE TITLE
Wifi Settings (Forget) not working

### ISSUE THREAD

**Issue by Eisbaeeer** [maakbaas/esp8266-iot-framework#136]
After select Wifi Settings Forget link, the framework will go to "captive portal" but after reboot, the framework will reconnect to stored Wifi. The stored Wifi settings will not be overwrite now.

**Comment by maakbaas** [comment]
Fixed. 

This was apparently caused by a breaking change in Arduino ESP8266 3.0:

> Starting from version 3 of this core, persistence is disabled by default

https://arduino-esp8266.readthedocs.io/en/latest/esp8266wifi/generic-class.html

**Comment by Eisbaeeer** [comment]
Ah, OK. Thank you for this Information. I remember for the issues with Version 3.
