### ISSUE TITLE
Adding "type": "password" in configuration

### ISSUE THREAD

**Issue by Eisbaeeer** [maakbaas/esp8266-iot-framework#141]
It will be more secure, if the password is hidden in configuration in case of passwords are used in text fields.
Or is there an other way to asterisk the text field?
Thank you.

**Comment by maakbaas** [comment]
Agreed. That one should be easy enough for you to put in a pull request :).

**Comment by Eisbaeeer** [comment]
Ahh, Ok. I will try my best ;-)

**Comment by Eisbaeeer** [comment]
There is nothing to do ;-) 
It is already usable with "control" like this:
`{
        "name": "password",
        "label": "Password",
        "type": "char",
        "length": 20,
        "value": "blabla",
        "control": "password"
    }`

**Comment by maakbaas** [comment]
Ok, I think that is an unintended functionality 😎, I'll look into this later

**Comment by maakbaas** [comment]
Addressed in c14776636073471e79461854988e1e522b0904a7
