### ISSUE TITLE
Detect if captive portal is running and WiFi is in Ad-hoc mode

### ISSUE THREAD

**Issue by marcolino7** [maakbaas/esp8266-iot-framework#146]
Hi,
I need to run different code if WiFi is configured and connected to an access point, or WiFi is not connected and Captive Portal is running for 1st Wifi Config.
Is there a way to achieve this? In there a variable to check or method to call?

Many Thanks in advance

Marco

**Comment by aaronse** [comment]
Hello @marcolino7, yep, can detect if wifi isn't configured already, take a look at WifiManager.cpp that uses WiFi.SSID()

Cheers!  aaron

**Comment by marcolino7** [comment]
Hi thanks,
I will look into

Thanks

**Comment by aaronse** [comment]
> Hi thanks, I will look into
> 
> Thanks

Also, could call WiFiManager.isCaptivePortal() from your setup/loop code
