### ISSUE TITLE
Separator and titol in config page

### ISSUE THREAD

**Issue by marcolino7** [maakbaas/esp8266-iot-framework#147]
Hi,
it would be great to have separator line and/or title in config page, to better group settings, in example General, MQTT, etc
To achieve this, a special json could be added to configuration.json, for example:

```
{
        "name": "-separator-"
},
{
        "name": "-heading-",
        "value": "MQTT",
},
```

This could be rendered and added to config page.

Thanks in advance
Marco

**Comment by maakbaas** [comment]
The fields below can be used for purposes of the HTML page (both in configuration.json and dashboard.json) and will have no functional impact:

```json
{
    "type": "separator"
},
{
    "type": "header",
    "text": "Header text here"
},
{
    "type": "label",
    "text": "Label text here"
},
```
