### ISSUE TITLE
WiFi passwords including "+" not working

### ISSUE THREAD

**Issue by pfichtner** [maakbaas/esp8266-iot-framework#155]
Trying to connect to an AP which has password (key) including "`+`" connections can not be established ("New connection unsuccessful"), no matter if I do via HTML-Webinterface or API-Call (`/api/wifi/set`). 
Perhaps this affects other special chars as well.

**Comment by maakbaas** [comment]
Should be fixed in 813418e

**Comment by pfichtner** [comment]
I can confirm that the problem is fixed now. 
Thank you!

**Comment by maakbaas** [comment]
Thanks for reporting the issue, and the feedback on the solution!
