### ISSUE TITLE
Import issue Arduino IDE 2.1.1

### ISSUE THREAD

**Issue by CaveRenderPro** [maakbaas/esp8266-iot-framework#166]
Importing your library to Arduino IDE 2.1.1 cause this error: "Error: 13 INTERNAL: Library install failed: moving extracted archive to destination dir: Bibliothek nicht gültig"

Do you have any idea?

**Comment by Eisbaeeer** [comment]
Hi. You have to use platformio instead of Arduino IDE.

**Comment by CaveRenderPro** [comment]
Thanks. As workaround for Arduino IDE I simply copy the source files to my sketch directory.

**Comment by maakbaas** [comment]
Workflows outside PlatformIO are at your own risk :).
