### ISSUE TITLE
Missing dependancy

### ISSUE THREAD

**Issue by riban-bw** [maakbaas/esp8266-iot-framework#170]
The project will not compile without ESP Async WebServer which is not mentioned in the README or example code. May I suggest adding explaination to the README that ESP Async WebServer should be added to platform.ini, e.g.

```
lib_deps =
	ESP8266 IoT Framework
	ESP Async WebServer
```

Or if possible (and probably better option) would be to add as a dependancy so that this library is automatically added when ESP8266 IoT Framework is specified as a dependancy.

**Comment by maakbaas** [comment]
Fixed in bc02314. 

In fact the correct dependency was listed as dependency already, but it seems the format of the library.json file was changed by PlatformIO, which is why it was no longer being handled as it should have.
