### ISSUE TITLE
Upload empty file failes

### ISSUE THREAD

**Issue by riban-bw** [maakbaas/esp8266-iot-framework#171]
An attempt to upload an empty (zero sized) file will fail. The upload page shows continous progress animation but nothing more happens.

**Comment by maakbaas** [comment]
I've quickly looked into this, but it seems as if the webserver does not trigger the onUpload callback in case the file is empty. This is at the side of the Async webserver library, so nothing I can fix right now. In any case, I guess uploading an empty file is not a common use case and you can just as well create a new file on the filesystem programmatically.
