### ISSUE TITLE
Thoughts on supporting ESP32?

### ISSUE THREAD

**Issue by aaronse** [maakbaas/esp8266-iot-framework#31]
Hello! @maakbaas, firstly thank you for creating and sharing this project.

Any thoughts on supporting ESP32?

Has anyone already done so?  Am digging around to see if anyone has already, and trying to grasp what's involved.  Am relatively new to ESPxx development.

Cheers!

**Comment by maakbaas** [comment]
Hi, thanks for your message. 

I have looked into this, and it would require significant rework to do this. In an ideal world, 'Arduino' is supposed to be an abstraction layer, meaning that the framework should work for both ESP8266 and ESP32 as long as the Arduino libraries are used. 

In reality this is not the case. There are a few significant differences between the Arduino implementation for both chips and therefore my code does not port to the ESP32. On example is the approach to do HTTPS requests. This method relies on BearSSL, but BearSSL is completely missing from the ESP32 Arduino libraries, so this can not be supported. 

If the ESP32 Arduino libraries are expanded in the future it can be reconsidered to make my framework compatible, but for now I am not planning to work on this.
