### ISSUE TITLE
Setting Up fixed IP Address

### ISSUE THREAD

**Issue by marcolino7** [maakbaas/esp8266-iot-framework#46]
Hi,
reading documentation is not clear how to setup a fixed IP address, from the code or from web interface. Is ti possible to do?

Thanks

**Comment by maakbaas** [comment]
This is indeed not yet supported. Is it needed for your use case? You are definitely encouraged to add this in a pull request, please let me know if you are open to that.

**Comment by marcolino7** [comment]
Hi @maakbaas 
thanks for reply. I'm stuck on another issue. I am not able to make MQTT working together with esp8266-iot-framework. I use PubSubClient.h and get compilation errore with async webserver adding this library. Do you have some example with MQTT?

Marco

**Comment by maakbaas** [comment]
This will be included in the next release, thanks for requesting this feature.
