### ISSUE TITLE
DashBoard 

### ISSUE THREAD

**Issue by FSCSoft** [maakbaas/esp8266-iot-framework#58]
[
![22790e7f-7440-4d8b-ab73-09f70bb4d659](https://user-images.githubusercontent.com/53421064/100299012-3784a700-2f58-11eb-97ef-604d188b127e.jpeg)
](url)

the dashboard does not work on mobile devices

**Comment by maakbaas** [comment]
Does the same page function on the desktop for you? Can you tell me what happens here, and why it does not work? What behavior do you expect, and what does it do? It seems surprising that there would be a difference between mobile and desktop, in my case on mobile it works just as well as on desktop. 

How does your JSON file look and your C code?

Do you see in the ESP8266 terminal that a new WS is connected when you go to this page from your mobile? Actually, the fact that the `live` label is shown indicates that there is a successful Websocket connection...

**Comment by FSCSoft** [comment]
Yes on desktop if it works perfectly I could only make it work in chrome dev in android for my thinking it can be the bintojson converter and if the connection to the websocket and api rest is fine because I can set the options

 

Sentek Ver.

**Comment by maakbaas** [comment]
Without providing more details in response to my earlier questions I am inclined to close this issue, because then it will be difficult to debug...

**Comment by FSCSoft** [comment]
If friend will be difficult debugging I agree

[dashboard.zip](https://github.com/maakbaas/esp8266-iot-framework/files/5609433/dashboard.zip)

**Comment by FSCSoft** [comment]
don't think about using arduinoJSON

**Comment by maakbaas** [comment]
and your C code?

**Comment by FSCSoft** [comment]
here it is
[WifiLavadora.zip](https://github.com/maakbaas/esp8266-iot-framework/files/5610054/WifiLavadora.zip)

**Comment by maakbaas** [comment]
Thanks for sharing. I tried your code on 2 different mobile phones (1 android and 1 iPhone) and in both cases it works as expected. Hopefully for you now the solution is acceptable to use Chrome dev for Android. If more people run into the same issue we can investigate further!

**Comment by FSCSoft** [comment]
Hello friend, it's me again and I think what the solution would be instead of converting to pass a string in websoket and maybe in api dash set of json format with only the name and value of each object { name: dumyFloat, value: 2.1},{...} etc. example or maybe to reduce characters {dumy: {value: 2.2}, input {value: true}, etc}. to pass the data in real values ​​and not go through the conversion and it is already an ArduinoJSON dependency of some libs of the project. sorry for my bad English
