### ISSUE TITLE
Serial output on Dashboard page ?

### ISSUE THREAD

**Issue by clabnet** [maakbaas/esp8266-iot-framework#66]
Hi,
it would be fantastic send to dashboard via websocket the serial.println for debug and information messages ...
Thanks maakbaas

**Comment by maakbaas** [comment]
I would make it into a separate page, but I agree it could be a nice addition

**Comment by maakbaas** [comment]
Pull requests to implement this remain welcome, but I will close this issue for now since I don't plan to work on this in the near future.
