### ISSUE TITLE
Firmware ugrade size

### ISSUE THREAD

**Issue by clabnet** [maakbaas/esp8266-iot-framework#69]
Hi maakbaas,
you say: "The firmware can be uploaded through the Browser to LittleFS and then flashed to the device."
How to upgrade our firmware if the current sketch size is over 90% ROM size ?

It fail miserably... We would implement a mode similar as TASMOTA upgrade. It download first a minimal fw from site to recovery space, install it, and then download finally the "fat" version with the latest version. 

Can it will possible on the future ? 

Thank's.

Claudio

**Comment by maakbaas** [comment]
Hi Clabnet, 

Sorry for the late response, I was quite busy the past few months. I understand your suggestion, and I agree it is more elegant to do it in the Tasmota way. However this is quite a departure from the current implementation, and something where I don't have the time to implement this. Of course, somebody else can take a shot. Potentially this can be combined with the partial implementation proposed in #38.
