### ISSUE TITLE
Cannot install it correctly on macOS Big Sur

### ISSUE THREAD

**Issue by varosi** [maakbaas/esp8266-iot-framework#70]
After installing the library via PlatfromIO on Visual Studio Code and when I try to build the project I get:
```
ModuleNotFoundError: No module named 'asn1crypto':
  File "/Users/home/.platformio/penv/lib/python3.8/site-packages/platformio/builder/main.py", line 170:
    env.SConscript("$BUILD_SCRIPT")
  File "/Users/home/.platformio/packages/tool-scons/scons-local-4.0.1/SCons/Script/SConscript.py", line 598:
    return _SConscript(self.fs, *files, **subst_kw)
```
I have already installed asn1crypto globally, but it's strange that this is a some other environment. My Python is 3.9, not 3.8. 
Is it possible this library to auto-install asn1crypto where is needed during installation process in Visual Studio Code?

**Comment by varosi** [comment]
The same happen on Windows also.

**Comment by maxgerhardt** [comment]
Just open a [PIO terminal](https://docs.platformio.org/en/latest/integration/ide/vscode.html#platformio-core-cli) and do a `pip3 install asn1crypto` -- PIO is running in it's own isolated penv

**Comment by varosi** [comment]
And this is the result:
`Requirement already satisfied: asn1crypto in /usr/local/lib/python3.9/site-packages (1.4.0)`

This still doesn't help.

**Comment by maxgerhardt** [comment]
> Requirement already satisfied: asn1crypto in /usr/local/lib/python3.9/site-packages (1.4.0)
>  File "/Users/home/.platformio/penv/lib/python3.8/site-packages/platformio/builder/main.py", line 170:

You're still using your global 3.9 installation and not the isolated 3.8 installation of PlatformIO. 

Try it this way in a normal terminal:
```
cd /Users/home/.platformio/penv/Scripts
./activate
./pip3 install asn1crypto
```

**Comment by varosi** [comment]
There is no "Scripts" folder there.

**Comment by maxgerhardt** [comment]
How did you install PlatformIO? Via the CLI first or just with the VSCode plugin?

**Comment by varosi** [comment]
VSCode plugin

**Comment by varosi** [comment]
There is /Users/home/.platformio/penv/ but without "Scripts". In "bin" folder there is "activate", but it's not executable.

**Comment by maxgerhardt** [comment]
Is a `pip3` executable file in this folder with which you can do `./pip3 install asn1crypto`?

**Comment by varosi** [comment]
Yes, there is, but it still give "Requirement already satisfied: asn1crypto in /usr/local/lib/python3.9/site-packages (1.4.0)"

**Comment by maxgerhardt** [comment]
Okay please post the output of `pio system info` when executed in a PIO terminal.

Otherwise you can try to replace this line 

https://github.com/maakbaas/esp8266-iot-framework/blob/4ef80a1c1ee1e99573cc14480b01ad87445ed013/scripts/preBuildCertificates.py#L7

with 
```py
try:
    from asn1crypto.x509 import Certificate
except ImportError:
    env.Execute(
        env.VerboseAction(
            '$PYTHONEXE -m pip install "asn1crypto" ',
            "ASN1 crypto import failed, installing.",
        )
    )
```


and try building twice (first to catch error + install, second to actually execute)

**Comment by varosi** [comment]
It worked! At least continued with the compilation.

Thanks a lot!
It could be easier I guess if the installation process of the library include that dependency automatically.

**Comment by maxgerhardt** [comment]
I've proposed that in PR #71  :)  

However, this should also be equivalent of executing `pio system info`, copying the value of the `Python Executable` entry and then appending `-m pip install asn1crypto` to it and executing it in a shell.

**Comment by maakbaas** [comment]
@maxgerhardt Thanks for supporting, and for the pull request. Indeed automatic installation of this dependency (and others) was already on my list for some time. I appreciate it!
