### ISSUE TITLE
Multiple language support

### ISSUE THREAD

**Issue by gabrielverani** [maakbaas/esp8266-iot-framework#73]
hello, I don't know if this is planned, but I would love to see a web app with multiple language support

**Comment by maakbaas** [comment]
Thanks for your suggestion. This has been implemented in PR #81.

There is now a parameter named `language` in the configuration.json file which can be used to set the language. Supported languages are placed in the folder `gui/js/lang`. Change the language code and rebuild the HTML interface to change the language. If your language is not yet supported, feel free to create a pull request for it.

The docs have been updated accordingly
