### ISSUE TITLE
Modify Webpage or add a button with Link

### ISSUE THREAD

**Issue by Eisbaeeer** [maakbaas/esp8266-iot-framework#80]
Great Framework! 
Is it possible to create a button as weblink in Dashboard?
`<a href="https://www.google.de" target="new">Open Goolge</a>`
E.g.  <a href="https://www.google.de" target="new">Open Goolge</a>
I tried that in dashboard but don´t get a link.
I need such solution to provide the user a Link.
Any example is welcome.
@maakbaas

**Comment by Eisbaeeer** [comment]
Ok, I checked, that I can provide e.g. an index.html to the /download/index.html by uploading a file via filemanager. This file will be presented in the users browser by using the "webServer.cpp. Is it possible to interact values between my code in loop and the webfile? Normaly I do that with `server.on("/config", getConfig);` or something else. But this will be done in the library and I will not change the whole lib. Is there a posibility to exchange values between the webinterface and my program? Don´t found something in the doc´s.
Greets

**Comment by maakbaas** [comment]
Hi Eisbaeeer,

With the framework it is definitely possible to add your own links or other elements to the web interface. But the only way in which this is supported is by modifying the web interface files directly. I do not plan to add other methods to add elements like a link. Can you explain why that would be a problem for you?
