### ISSUE TITLE
CLion, platformio, python and `pip install asn1crypto`

### ISSUE THREAD

**Issue by jbanaszczyk** [maakbaas/esp8266-iot-framework#86]
That is incredible project. Many, many thanks :)

Using:
* Windows
* CLion from JetBrains
* Platformio

There is an unexpected behavior. CLion Platformio plugin uses system-wide python `C:\Program Files\Python37\python.EXE`
$PYTHONEXE should be quoted

**Comment by maakbaas** [comment]
Thanks for reporting, and thanks for proposing the fix. This will be added to the next release (including your openssl change, which is also appreciated :)).
