### ISSUE TITLE
config values reverts to previous value after a few successful saves and restart ESP8266

### ISSUE THREAD

**Issue by cychrn** [maakbaas/esp8266-iot-framework#96]
I found an issue about the configManager when i try to save the second time, it reverts to previous value after restart

this is how to reproduce the issue

1. Erase flash
2. Upload code
3. save Wifi credential
4. go to config page and change any config and hit the save button
5. restart
6. go to config page and see the config value is changed normally
7. loop 4-6 for 4 more times
8. you will see that the config cannot be saved anymore...

is there anything i did wrong? or the memory is full? please advise...

**Comment by maakbaas** [comment]
I just tried this for 10 times, and I can't reproduce it. More details would be needed :).
