### ISSUE TITLE
Float number displayed on Dashboard with garbage number after the 6th decimal point

### ISSUE THREAD

**Issue by cychrn** [maakbaas/esp8266-iot-framework#98]
I have an issue displaying a floating number (temperature and humidity) with 1 decimal point on Dashboard

The reading from sensor is with 1 decimal point. but when it displays on dashboard, it display weird number after the 6th decimal point

27.2 -> 27.200000762939453
59.6 -> 57.599998474121094

![image](https://user-images.githubusercontent.com/50680667/112164538-88638e00-8c20-11eb-9dc8-e282b329d013.png)

I have tried manipulating the number to remove the decimal points after the 6th digit still it was not working out...

could you please advise how to overcome this?

thank you very much in advanced.

**Comment by maakbaas** [comment]
Hi,

This was discussed in #61.

you can add a `digits` field to your JSON file to specify the number of digits that should be shown in the interface. This is also mentioned in the documentation.
